version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: commerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: commerce
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis_cache:
    image: redis:7-alpine
    container_name: commerce_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  